apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-privatekey
  namespace: ece440spring2024-619f12
spec:
  secretStoreRef:
    name: nerc-secret-store
    kind: SecretStore
  target:
    name: ssh-privatekey
  data:
  - secretKey: ssh-privatekey
    remoteRef:
      key: nerc/nerc-ocp-prod/ece440spring2024-619f12/ssh-privatekey
      property: ssh-privatekey